### ISSUE TITLE
Incompatible with tag-bag v2

### ISSUE THREAD

**Issue by LucaGallinari** [Setono/tag-bag-twig#2]
It would be great to have a compatible version with tag-bag v2🙂

**Comment by loevgaard** [comment]
By default you shouldn't need this library in tag bag v2. There's a twig renderer in the tag bag bundle by default if you need it: https://github.com/Setono/TagBagBundle/blob/3.x/src/Renderer/TwigRenderer.php. So if your tags implement the `TemplateTagInterface` I think you should be fine. Let me know if there's something I am missing :)

**Comment by LucaGallinari** [comment]
wow good, i'll take a look

**Comment by loevgaard** [comment]
Did it work? :) If yes, you can close this issue.

**Comment by LucaGallinari** [comment]
I'll try it next week, but until proven otherwise this is not a real issue
Thanks!
